services:
    anavarocom.zebraenhance.listener:
        class: anavarocom\zebraenhance\event\zebra_listener
        arguments:
            - @user_loader
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - @anavarocom.zebraenhance.notifyhelper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
        tags:
            - { name: event.listener }
    anavarocom.zebraenhance.ajaxyfy:
        class: anavarocom\zebraenhance\controller\ajaxify
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    anavarocom.zebraenhance.notifyhelper:
        class: anavarocom\zebraenhance\controller\notifyhelper
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    notification.type.zebraadd:
        class: anavarocom\zebraenhance\notification\zebraadd
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
    
    notification.type.zebraconfirm:
        class: anavarocom\zebraenhance\notification\zebraconfirm
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }